### ISSUE TITLE
标定数据

### ISSUE THREAD

**Issue by lixiaodongcq** [ZixuanLiang/inappropriate_content_detect#1]
您好，我现在有一些标定数据，请问如果我想继续训练你的模型，应该如何标定数据呢？

**Comment by ZixuanLiang** [comment]
训练集文件夹TRAIN_DIR下，每个分类建一个文件夹，把标定数据放进去。
验证集文件夹VALID_DIR同理。

**Comment by lixiaodongcq** [comment]
我测试了一下你的不良图片模型识别率。结果就是准确率可以，但是你的误报率比较高。就是说容易把正常图片判断为不良图片。误报率在60%以上。我现在有标定的不良图片，叫做正样本，同时也需要训练负样本嘛？如果需要训练，怎么样负样本放到网络里面进行训练呢

**Comment by ZixuanLiang** [comment]
误报率高是因为训练数据没有经过人工筛选，而且数据的代表性不一定好，我是自动从网站下载的，这个模型只是第一个版本。调阈值可以牺牲一些召回率以减少误报。你用精准的数据训练会有更好的效果，比如黄色图片，正负样本数量要一致，都应该包含各种类型的，比如负样本包含正常的图片、性感的图片、穿泳装的人、赤裸的婴儿等等，以提高准确率。在训练集文件夹和验证集文件夹下，负样本和正样本放在各自的文件夹里就可以训练了。
